#! /bin/sh

logger -t bspwmrc "started running bspwmrc..."

# --- SXHKD ---
pgrep -x sxhkd > /dev/null
if [ $? -eq 0 ]; then
    logger -t bspwmrc "sxhkd is already running, will not start"
else
    sxhkd &
    logger -t bspwmrc "started sxhkd in background"
fi

# --- BSPC CONFIG ---
logger -t bspwmrc "starting bspc config..."

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap           12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color "#A3BE8C"

logger -t bspwmrc "finished bspc config"

logger -t bspwmrc "finished running bspwmrc"
